// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_SelectingData.Models;

public partial class Anime
{
    public int AnimeId { get; set; }

    public string Name { get; set; }

    public string Genre { get; set; }

    public string Type { get; set; }

    public double? Episodes { get; set; }

    public double? Rating { get; set; }

    public double? Members { get; set; }
}