// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Database_SelectingData.Models;

public partial class DB_128040_practiceContext : DbContext
{
    public DB_128040_practiceContext()
    {
    }

    public DB_128040_practiceContext(DbContextOptions<DB_128040_practiceContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Anime> Animes { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Director> Directors { get; set; }

    public virtual DbSet<FootballSchedule> FootballSchedules { get; set; }

    public virtual DbSet<Manufacturer> Manufacturers { get; set; }

    public virtual DbSet<MigrationHistory> MigrationHistories { get; set; }

    public virtual DbSet<Movie> Movies { get; set; }

    public virtual DbSet<Registration> Registrations { get; set; }

    public virtual DbSet<Spotify> Spotifies { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    { //=> optionsBuilder.UseSqlServer("Data Source=tcp:s13.winhost.com;Initial Catalog=DB_128040_practice;Persist Security Info=True;User ID=student;Password=AdamTheGreat2020");
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(
               "Data Source=tcp:s13.winhost.com;" +
               "Initial Catalog=DB_128040_practice;" +
               "Persist Security Info=True;" +
               "User ID=student;" +
               "Password=AdamTheGreat2020;" +
               "Encrypt=True;" +
               "TrustServerCertificate=True");

        }
    }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Anime>(entity =>
        {
            entity.ToTable("Anime");

            entity.Property(e => e.AnimeId)
                .ValueGeneratedNever()
                .HasColumnName("anime_id");
            entity.Property(e => e.Episodes).HasColumnName("episodes");
            entity.Property(e => e.Genre)
                .HasMaxLength(255)
                .HasColumnName("genre");
            entity.Property(e => e.Members).HasColumnName("members");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.Type)
                .HasMaxLength(255)
                .HasColumnName("type");
        });

        modelBuilder.Entity<Course>(entity =>
        {
            entity.ToTable("Course");

            entity.Property(e => e.CourseId).HasColumnName("CourseID");
            entity.Property(e => e.CourseName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CourseNumber)
                .IsRequired()
                .HasMaxLength(10)
                .IsFixedLength();
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable("Customer");

            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Gender)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.State)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ZipCode).HasMaxLength(10);
        });

        modelBuilder.Entity<Director>(entity =>
        {
            entity.ToTable("Director");

            entity.Property(e => e.DirectorId)
                .ValueGeneratedNever()
                .HasColumnName("Director_Id");
            entity.Property(e => e.DirectorName)
                .IsRequired()
                .HasMaxLength(150)
                .HasColumnName("Director_Name");
        });

        modelBuilder.Entity<FootballSchedule>(entity =>
        {
            entity.ToTable("FootballSchedule");

            entity.Property(e => e.Opponent)
                .IsRequired()
                .HasMaxLength(50)
                .IsFixedLength();
        });

        modelBuilder.Entity<Manufacturer>(entity =>
        {
            entity.ToTable("Manufacturer");

            entity.Property(e => e.ManufacturerId).HasColumnName("ManufacturerID");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.City)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Contact)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ManufacturerName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(14);
            entity.Property(e => e.PostalCode)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.State)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Url)
                .HasMaxLength(150)
                .HasColumnName("URL");
        });

        modelBuilder.Entity<MigrationHistory>(entity =>
        {
            entity.HasKey(e => new { e.MigrationId, e.ContextKey }).HasName("PK_dbo.__MigrationHistory");

            entity.ToTable("__MigrationHistory");

            entity.Property(e => e.MigrationId).HasMaxLength(150);
            entity.Property(e => e.ContextKey).HasMaxLength(300);
            entity.Property(e => e.Model).IsRequired();
            entity.Property(e => e.ProductVersion)
                .IsRequired()
                .HasMaxLength(32);
        });

        modelBuilder.Entity<Movie>(entity =>
        {
            entity.ToTable("Movie");

            entity.Property(e => e.MovieId).HasColumnName("Movie_Id");
            entity.Property(e => e.Actor1FacebookLikes).HasColumnName("actor_1_facebook_likes");
            entity.Property(e => e.Actor1Name)
                .HasMaxLength(150)
                .HasColumnName("actor_1_name");
            entity.Property(e => e.Actor2FacebookLikes).HasColumnName("actor_2_facebook_likes");
            entity.Property(e => e.Actor2Name)
                .HasMaxLength(150)
                .HasColumnName("actor_2_name");
            entity.Property(e => e.Actor3FacebookLikes).HasColumnName("actor_3_facebook_likes");
            entity.Property(e => e.Actor3Name)
                .HasMaxLength(150)
                .HasColumnName("actor_3_name");
            entity.Property(e => e.AspectRatio)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("aspect_ratio");
            entity.Property(e => e.Budget).HasColumnName("budget");
            entity.Property(e => e.CastTotalFacebookLikes).HasColumnName("cast_total_facebook_likes");
            entity.Property(e => e.Color)
                .HasMaxLength(150)
                .HasColumnName("color");
            entity.Property(e => e.ContentRating)
                .HasMaxLength(150)
                .HasColumnName("content_rating");
            entity.Property(e => e.Country)
                .HasMaxLength(150)
                .HasColumnName("country");
            entity.Property(e => e.DirectorFacebookLikes).HasColumnName("director_facebook_likes");
            entity.Property(e => e.DirectorId).HasColumnName("director_id");
            entity.Property(e => e.Duration).HasColumnName("duration");
            entity.Property(e => e.FacenumberInPoster).HasColumnName("facenumber_in_poster");
            entity.Property(e => e.Genres)
                .HasMaxLength(150)
                .HasColumnName("genres");
            entity.Property(e => e.Gross).HasColumnName("gross");
            entity.Property(e => e.ImdbScore)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("imdb_score");
            entity.Property(e => e.Language)
                .HasMaxLength(150)
                .HasColumnName("language");
            entity.Property(e => e.MovieFacebookLikes).HasColumnName("movie_facebook_likes");
            entity.Property(e => e.MovieImdbLink)
                .HasMaxLength(150)
                .HasColumnName("movie_imdb_link");
            entity.Property(e => e.MovieTitle)
                .HasMaxLength(150)
                .HasColumnName("movie_title");
            entity.Property(e => e.NumCriticForReviews).HasColumnName("num_critic_for_reviews");
            entity.Property(e => e.NumUserForReviews).HasColumnName("num_user_for_reviews");
            entity.Property(e => e.NumVotedUsers).HasColumnName("num_voted_users");
            entity.Property(e => e.PlotKeywords)
                .HasMaxLength(150)
                .HasColumnName("plot_keywords");
            entity.Property(e => e.TitleYear).HasColumnName("title_year");

            entity.HasOne(d => d.Director).WithMany(p => p.Movies)
                .HasForeignKey(d => d.DirectorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Movie_Director");
        });

        modelBuilder.Entity<Registration>(entity =>
        {
            entity.ToTable("Registration");

            entity.Property(e => e.RegistrationId).HasColumnName("RegistrationID");
            entity.Property(e => e.CourseId).HasColumnName("CourseID");
            entity.Property(e => e.EnrollmentDate).HasColumnType("datetime");
            entity.Property(e => e.StudentId).HasColumnName("StudentID");

            entity.HasOne(d => d.Course).WithMany(p => p.Registrations)
                .HasForeignKey(d => d.CourseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Registration_Course");

            entity.HasOne(d => d.Student).WithMany(p => p.Registrations)
                .HasForeignKey(d => d.StudentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Registration_Student");
        });

        modelBuilder.Entity<Spotify>(entity =>
        {
            entity.HasKey(e => e.Index);

            entity.ToTable("Spotify");

            entity.Property(e => e.Index).ValueGeneratedNever();
            entity.Property(e => e.Artist).HasMaxLength(255);
            entity.Property(e => e.BeatsPerMinute).HasColumnName("Beats Per Minute");
            entity.Property(e => e.Title).HasMaxLength(255);
            entity.Property(e => e.TopGenre)
                .HasMaxLength(255)
                .HasColumnName("Top Genre");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.ToTable("Student");

            entity.Property(e => e.StudentId).HasColumnName("StudentID");
            entity.Property(e => e.FavoriteColor).HasMaxLength(15);
            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.LastName).HasMaxLength(30);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}