// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Database_SelectingData.Models;

public partial class Spotify
{
    public int Index { get; set; }

    public string Title { get; set; }

    public string Artist { get; set; }

    public string TopGenre { get; set; }

    public double? Year { get; set; }

    public double? BeatsPerMinute { get; set; }

    public double? Energy { get; set; }

    public double? Danceability { get; set; }

    public double? Loudness { get; set; }

    public double? Liveness { get; set; }

    public double? Valence { get; set; }

    public double? Duration { get; set; }

    public double? Acousticness { get; set; }

    public double? Speechiness { get; set; }

    public double? Popularity { get; set; }
}