// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DB_Associative_Populating.Models;

public partial class Dog
{
    public Dog()
    {
        DogToys = new HashSet<DogToy>();
    }

    public Dog(DogInput dog) : this()
    {
        //Id = dog.Id;
        Name = dog.Name;
        Breed = dog.Breed;
        Image = dog.Image;
        OwnerId = dog.OwnerId;
    }

    public int Id { get; set; }

    public string Name { get; set; }

    public string Breed { get; set; }

    public string Image { get; set; }

    public int? OwnerId { get; set; }

    public override string ToString()
    {
        return $"{Name} : {Breed} owned by {OwnerId}";
    }

    public virtual ICollection<DogToy> DogToys { get; set; } = new List<DogToy>();

    public virtual Owner Owner { get; set; }
}